from app import models, utilities
from .ticket_cost_calculator import get_ticket_cost
from sqlalchemy import and_
import datetime


# gets the total income generated by the cinema from its opening up to the current date
def get_total_income(cumulative=False):
    cinema_opening = datetime.datetime(year=2021, month=1, day=1)
    today = datetime.datetime.now()
    number_days = (today - cinema_opening).days
    # list of incomes at each datapoint
    incomes = []
    current_date = cinema_opening
    income = 0
    for i in range(number_days):
        current_date += datetime.timedelta(days=1)
        if not cumulative:
            income = 0
        transactions = models.Transaction.query.filter(and_(models.Transaction.date>=current_date, models.Transaction.date <= current_date + datetime.timedelta(hours=23, minutes=59))).all()
        for transaction in transactions:
            reservations = models.Reservation.get_by_transaction_id(transaction.id)
            for reservation in reservations:
                showing = models.Showing.get_by_showing_id(reservation.showing_id)
                tickets = models.Ticket.get_by_reservation_id(reservation.id)
                for ticket in tickets:
                    ticket_cost = get_ticket_cost(showing, ticket)
                    income += ticket_cost
        timestamp = current_date.replace(tzinfo=datetime.timezone.utc).timestamp()

        incomes.append((timestamp, income))
    return incomes
